Fix compiler error with release builds on VS2015
When using MSVC compiler optimization, using param_not_found() causes
compiler error C4172: returning address of local variable or temporary